import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {spawnSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';

const script=fileURLToPath(new URL('../plugins/greenfield/skills/session-trace/scripts/build-trace.mjs',import.meta.url));
test('trace foregrounds escaped conversation text while tool details remain collapsed',t=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'greenfield-trace-'));
 t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));
 const session=path.join(dir,'session.jsonl');
 const row=(n,type,payload)=>({timestamp:`2026-09-23T12:00:0${n}Z`,type,payload});
 const message=(role,text)=>({type:'message',role,content:[{type:role==='user'?'input_text':'output_text',text}]});
 const rows=[row(0,'session_meta',{id:'fixture',cwd:dir}),row(1,'response_item',message('user','Please fix <script>alert(1)</script>')),row(2,'response_item',message('assistant','Checking the renderer.')),row(3,'response_item',{type:'function_call',name:'exec',call_id:'c1',arguments:'{"cmd":"echo checked"}'}),row(4,'response_item',{type:'function_call_output',call_id:'c1',output:'checked'}),row(5,'response_item',message('assistant','Fixed the rendering.'))];
 rows.splice(2,0,row(1,'response_item',{...message('assistant','PRIVATE REASONING'),channel:'analysis'}));
 fs.writeFileSync(session,rows.map(x=>JSON.stringify(x)).join('\n'));
 const result=spawnSync(process.execPath,[script,'--session',session,'--out',dir],{encoding:'utf8',env:{...process.env,HOME:dir,USERPROFILE:dir}});
 assert.equal(result.status,0,result.stderr);
 const html=fs.readFileSync(path.join(dir,'trace.html'),'utf8');
 assert.match(html,/<details class="turn" open id="t0"/);
 assert.match(html,/<strong>User<\/strong>/);
 assert.match(html,/<strong>Agent<\/strong>/);
 assert.doesNotMatch(html,/PRIVATE REASONING/);
 assert.match(html,/Checking the renderer\./);
 assert.match(html,/Fixed the rendering\./);
 assert.match(html,/&lt;script&gt;alert\(1\)&lt;\/script&gt;/);
 assert.doesNotMatch(html,/<script>alert\(1\)<\/script>/);
 assert.match(html,/<details class="tool-calls"><summary>1 tool calls<\/summary>/);
 assert.doesNotMatch(html,/<details class="tool-calls"[^>]*\bopen\b/);
});
