import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
import {ProfileManager} from '../dist/profile-manager.js';
import {startTelemetryUI} from '../dist/telemetry-ui.js';

function fixture(t){const root=fs.realpathSync.native(fs.mkdtempSync(path.join(os.tmpdir(),'farm-profiles-')));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));for(const dir of ['agents','profiles','project','.plugins','plugins/demo/agents','plugins/demo/profiles'])fs.mkdirSync(path.join(root,dir),{recursive:true});fs.writeFileSync(path.join(root,'agents/builder.md'),'---\nharness: claude\nmodel: sonnet\n---\nBuild carefully.\n');fs.writeFileSync(path.join(root,'profiles/builder.yaml'),'# Preserve this comment\nagent: builder\n');fs.writeFileSync(path.join(root,'plugins/demo/plugin.yaml'),'name: demo\nversion: 1.0.0\ncli_major: 0\n');fs.writeFileSync(path.join(root,'.plugins/demo.json'),JSON.stringify({name:'demo',version:'1.0.0',layout:2}));fs.writeFileSync(path.join(root,'plugins/demo/agents/planner.md'),'---\nharness: codex\nmodel: gpt-5\n---\nPlan carefully.\n');fs.writeFileSync(path.join(root,'plugins/demo/profiles/planner.yaml'),'agent: planner\n');return {root,project:path.join(root,'project'),manager:new ProfileManager(root,path.join(root,'project'))};}

test('profile manager previews without writes, creates and edits validated presets, preserves comments',t=>{const {root,manager}=fixture(t),current=manager.get('builder');assert.equal(manager.list().length,2);assert.deepEqual(manager.agents(),['builder','demo/planner']);assert.equal(current.resolved.harness,'claude');assert.equal(current.resolved.instructions,'Build carefully.');const input={name:'reviewer',source:'agent: builder\nmodel:\n  name: opus\n',revision:null};assert.equal(manager.preview(input).resolved.model.name,'opus');assert.equal(fs.existsSync(path.join(root,'profiles/reviewer.yaml')),false);manager.save(input);assert.throws(()=>manager.save(input),/already exists/);const composed=manager.compose({source:current.source,agent:'builder',model:'opus',reasoning:'',speed:'',args:'{}'});assert.match(composed.source,/# Preserve this comment/);manager.save({name:'builder',source:composed.source,revision:current.revision});assert.equal(manager.get('builder').resolved.model.name,'opus');assert.throws(()=>manager.save({name:'builder',source:current.source,revision:current.revision}),/changed on disk/);assert.match(fs.readFileSync(path.join(root,'agents/builder.md'),'utf8'),/model: sonnet/);});

test('plugin duplicates retain qualified references; plugin sources cannot be overwritten',t=>{const {manager}=fixture(t),plugin=manager.get('demo/planner');assert.equal(plugin.readOnly,true);const copy=manager.duplicate('demo/planner');assert.match(copy.source,/agent: demo\/planner/);const result=manager.save({name:'my-planner',source:copy.source,revision:null});assert.equal(result.resolved.harness,'codex');assert.throws(()=>manager.save({name:'demo/planner',source:copy.source,revision:plugin.revision}),/not a path/);});

test('profile validation enforces workspace trust without granting approval',t=>{const {root,project,manager}=fixture(t);execFileSync('git',['init','-q',project]);fs.mkdirSync(path.join(project,'.agent-farm'));fs.writeFileSync(path.join(project,'.agent-farm/workspace.yaml'),'name: untrusted-preview\ninstructions: Do not load without trust\n');assert.throws(()=>manager.save({name:'blocked',source:'agent: builder',revision:null}),/trust|approv/i);assert.equal(fs.existsSync(path.join(root,'profiles/blocked.yaml')),false);assert.match(manager.get('builder').error,/trust|approv/i);});

test('invalid profiles, paths, stale revisions, symlinks and oversized documents never write',t=>{const {root,manager}=fixture(t);for(const source of ['agent: missing','agent: builder\nextra: true','agent: builder\nagent: builder','agent: builder\nargs:\n  nope: yes','x'.repeat(65537)])assert.throws(()=>manager.save({name:'bad',source,revision:null}));assert.equal(fs.existsSync(path.join(root,'profiles/bad.yaml')),false);assert.throws(()=>manager.preview({name:'../escape',source:'agent: builder',revision:null}),/not a path/);fs.symlinkSync(path.join(root,'profiles/builder.yaml'),path.join(root,'profiles/link.yaml'));assert.throws(()=>manager.save({name:'link',source:'agent: builder',revision:null}),/symlink/);fs.renameSync(path.join(root,'profiles'),path.join(root,'original-profiles'));fs.symlinkSync(path.join(root,'original-profiles'),path.join(root,'profiles'));assert.throws(()=>manager.preview({name:'new',source:'agent: builder',revision:null}),/symlink/);});

test('management HTTP requires token, origin, method and bounded JSON; telemetry remains read-only',async t=>{const {root,project}=fixture(t),options={directory:path.join(root,'telemetry'),projectDirectory:project,scope:'project'},ui=await startTelemetryUI(options,0,{configRoot:root,projectDirectory:project});t.after(()=>new Promise(r=>ui.server.close(r)));const origin=new URL(ui.url).origin,input={name:'new',source:'agent: builder\n',revision:null},headers={'Content-Type':'application/json',Origin:origin,'X-Agent-Farm-UI':'1'};assert.match(await(await fetch(ui.url)).text(),/profile-manager/);assert.equal((await fetch(ui.url+'api/profiles/list')).status,200);assert.equal((await fetch(origin+'/api/profiles/list')).status,404);assert.equal((await fetch(ui.url+'api/profiles/save',{method:'POST',body:JSON.stringify(input)})).status,403);assert.equal((await fetch(ui.url+'api/profiles/save',{method:'POST',headers:{...headers,Origin:'https://example.org'},body:JSON.stringify(input)})).status,403);assert.equal((await fetch(ui.url+'api/profiles/save')).status,405);assert.equal((await fetch(ui.url+'api/profiles/save',{method:'POST',headers,body:JSON.stringify(input)})).status,200);assert.equal((await fetch(ui.url+'api/profiles/save',{method:'POST',headers,body:JSON.stringify({...input,name:'large',source:'a'.repeat(100000)})})).status,413);assert.equal((await fetch(ui.url+'api/runs',{method:'POST',headers,body:'{}'})).status,405);const readOnly=await startTelemetryUI(options);t.after(()=>new Promise(r=>readOnly.server.close(r)));assert.equal((await fetch(readOnly.url+'api/profiles/save',{method:'POST',headers,body:JSON.stringify(input)})).status,403);});
