import {telemetryPage} from './telemetry-ui-page.js';

export const uiPage=telemetryPage.replace('<title>Agent Farm · Sessions</title>','<title>Agent Farm</title>').replace('</style>',String.raw`
:root{--ink:#17223b;--muted:#65718a;--line:#e1e6ed;--green:#087747;--wash:#fff;--accent:#dff2e8}
body{background:white}.topbar{margin-left:190px;background:#fff;color:var(--ink);border-bottom:1px solid var(--line);height:56px;padding:0 22px}.topbar small{color:var(--muted)}.topbar .logo{display:none}.topbar .brand{font-size:14px}.app-nav{position:fixed;inset:0 auto 0 0;width:190px;background:#eef2f6;border-right:1px solid var(--line);padding:20px 10px;display:flex;flex-direction:column;gap:6px}.app-brand{font-weight:700;font-size:18px;padding:0 10px 26px}.app-brand span{color:var(--green);margin-right:9px}.app-nav a{padding:10px 14px;border-radius:5px;text-decoration:none;color:var(--ink);font-weight:550}.app-nav a[aria-current=true]{background:#cfe6dc;box-shadow:inset 3px 0 var(--green)}.app-nav small{padding:8px 14px;color:var(--muted)}.app-nav footer{margin-top:auto;font-size:12px;padding:12px;color:var(--muted)}.shell,#profile-manager{margin-left:190px;height:calc(100vh - 56px)}.sidebar,.structure{background:#fbfcfe}.session-link[aria-current=true],.tree-link[aria-current=true]{background:#e0f2e8;border-color:#cfe6dc}.session-link{border-radius:3px;border-bottom:1px solid #edf0f4}.session-link:hover{background:#f0f4f8}.reader{padding:22px}.reader h1{color:#111b31}.stats{border-radius:7px}.content-section>summary{color:var(--ink)}.document pre,pre.raw{background:#f3f6f9}.badge{background:#def3e7;color:#087747}.turn,.content-section{border-radius:6px}.structure{width:190px}.explorer-layout{grid-template-columns:190px minmax(0,1fr)}
#profile-manager{display:grid;grid-template-columns:280px minmax(0,1fr)}.profile-list{border-right:1px solid var(--line);overflow:auto;background:#fbfcfe;padding:16px 12px}.profile-list h1{font-size:20px;margin:0 0 14px}.profile-list input{width:100%;margin-bottom:10px}.profile-list .primary{width:100%;margin-bottom:18px}.profile-list h3{font-size:10px;letter-spacing:1.2px;text-transform:uppercase;color:var(--muted);margin:18px 8px 8px}.profile-link{display:block;padding:9px 10px;text-decoration:none;color:var(--ink);border-bottom:1px solid var(--line);font-size:13px}.profile-link strong,.profile-link small{display:block;overflow-wrap:anywhere}.profile-link small{color:var(--muted);font-size:11px;margin-top:3px}.profile-link[aria-current=true]{background:var(--accent);box-shadow:inset 3px 0 var(--green)}.profile-editor{padding:26px 32px 90px;overflow:auto;min-width:0}.profile-editor h1{margin:0;font-size:26px;letter-spacing:-.6px}.profile-editor h2{font-size:16px;margin:24px 0 14px}.profile-editor .editor-head{display:flex;justify-content:space-between;gap:12px;align-items:start}.profile-editor .subtitle{font-size:12px;color:var(--muted);margin:8px 0 20px;overflow-wrap:anywhere}.profile-editor label{display:block;font-size:12px;font-weight:600}.profile-editor label small{display:block;font-weight:400;color:var(--muted);margin:5px 0}.profile-editor input,.profile-editor select,.profile-editor textarea{width:100%;margin-top:6px}.profile-editor textarea{font:12px/1.7 ui-monospace,monospace;min-height:110px;border:1px solid var(--line);border-radius:6px;padding:12px;color:var(--ink);background:#fff;resize:vertical}.profile-editor textarea.source{min-height:260px}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.editor-panel{border:1px solid var(--line);padding:20px;border-radius:7px;max-width:1000px}.primary{background:#087747;color:white;border-color:#087747}.primary:hover:not(:disabled){background:#065e38}.save-bar{display:flex;justify-content:space-between;align-items:center;gap:12px;padding:16px 0;margin-top:16px;border-top:1px solid var(--line)}.review-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.review-grid pre{max-height:350px}.profile-editor pre{white-space:pre-wrap;overflow-wrap:anywhere}.error-panel{color:#9d3434;background:#fff4f4;border:1px solid #efd5d5;padding:12px;border-radius:6px;margin:12px 0}.resolved-section{border:1px solid var(--line);border-radius:6px;padding:12px 16px;margin:12px 0}.resolved-section summary{cursor:pointer;font-weight:600;font-size:12px}.resolved-section pre{font:12px/1.7 ui-monospace,monospace}.profile-editor button{font-size:12px}.profile-editor .tabs{margin-top:24px}.app-nav a:focus-visible{outline:3px solid #51a77c}
#workspace-label{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;display:block}.profile-editor input:disabled{background:#f5f7fa;color:var(--muted)}
@media(max-width:1100px){.app-nav{width:150px}.topbar,.shell,#profile-manager{margin-left:150px}#profile-manager{grid-template-columns:230px minmax(0,1fr)}.profile-editor{padding:22px}.app-brand{font-size:15px}.explorer-layout{display:block}.structure{width:auto;max-height:180px;overflow:auto;border-bottom:1px solid var(--line)}}
@media(max-width:700px){.app-nav{position:static;width:auto;flex-direction:row;align-items:center;padding:8px}.app-brand{padding:0 8px;font-size:14px}.app-nav small,.app-nav footer{display:none}.topbar,.shell,#profile-manager{margin-left:0}.topbar{height:44px}.shell,#profile-manager{height:auto}#profile-manager{display:block}.profile-list{max-height:32vh}.form-grid,.review-grid{grid-template-columns:1fr}.profile-editor{padding:20px 16px}.app-nav a{font-size:12px}.topbar .brand{font-size:12px}}
</style>`).replace('<body>','<body><nav class="app-nav" aria-label="Agent Farm"><div class="app-brand"><span aria-hidden="true">♧</span>Agent Farm</div><small>WORKSPACE</small><small id="workspace-label">Local configuration</small><a id="nav-sessions" href="#view=sessions">Sessions</a><a id="nav-profiles" href="#view=profiles">Profiles</a><footer>● Local only<br>agent-farm ui</footer></nav>').replace('LOCAL TELEMETRY · READ ONLY','LOCAL ONLY').replace('<span style="font-weight:400">Sessions</span>','<span id="view-title" style="font-weight:400">Sessions</span>').replace('<div id="status"','<section id="profile-manager" hidden aria-label="Profile manager"><aside class="profile-list"><h1>Profiles</h1><input id="profile-search" placeholder="Search profiles…" aria-label="Search profiles"><button id="new-profile" class="primary">＋ New profile</button><nav id="profile-list" aria-label="Profiles"></nav></aside><main id="profile-editor" class="profile-editor"></main></section><div id="status"');

// Serialized after compilation. Browser code must remain self-contained.
export function managementBrowser(){
  type Data=Record<string,any>;
  const $=(id:string)=>document.getElementById(id)!;
  let profiles:Data[]=[],agents:string[]=[],current:Data|undefined,dirty=false,sequence=0,lastHash=location.hash,editVersion=0;
  const el=(tag:string,text:string,parent:HTMLElement,cls='')=>{const e=document.createElement(tag);e.textContent=text;e.className=cls;parent.append(e);return e;};
  const button=(text:string,parent:HTMLElement,fn:()=>void,cls='')=>{const b=el('button',text,parent,cls) as HTMLButtonElement;b.type='button';b.onclick=fn;return b;};
  async function api(route:string,input?:Data){const r=await fetch('api/profiles/'+route,input?{method:'POST',headers:{'Content-Type':'application/json','X-Agent-Farm-UI':'1'},body:JSON.stringify(input)}:{});const value=await r.json();if(!r.ok)throw Error(value.error??'Request failed');return value;}
  function error(e:unknown){$('status').textContent=e instanceof Error?e.message:String(e);}
  function field(label:string,parent:HTMLElement,value='',hint=''){const l=el('label',label,parent);if(hint)el('small',hint,l);const input=el('input','',l) as HTMLInputElement;input.value=value;input.oninput=()=>{dirty=true;};return input;}
  function renderList(){const root=$('profile-list');root.replaceChildren();const search=($('profile-search') as HTMLInputElement).value.toLowerCase();for(const plugin of [false,true]){const group=profiles.filter(p=>!!p.plugin===plugin&&p.name.toLowerCase().includes(search));if(!group.length)continue;el('h3',plugin?'Plugin profiles · read only':'Local profiles',root);for(const p of group){const a=el('a','',root,'profile-link') as HTMLAnchorElement;a.href='#'+new URLSearchParams({view:'profiles',profile:p.name});a.setAttribute('aria-current',String(p.name===current?.name));a.onclick=e=>{if(dirty&&!confirm('Discard unsaved profile changes?'))e.preventDefault();else dirty=false;};el('strong',p.name,a);el('small',p.error?'Needs attention':p.harness+' · '+p.model,a);}}if(!root.children.length)el('p','No profiles yet. Create a profile using an existing agent definition.',root,'muted');}
  function resolved(value:Data,parent:HTMLElement){if(!value)return;for(const [title,content,open] of [['Effective configuration',{agent:value.agent,harness:value.harness,model:value.model,args:value.args,subagents:value.subagents},true],['Instructions · from agent and workspace',value.instructions,false],['Skills · from agent',value.skills,false],['Telemetry access · workspace policy',value.telemetry_access,false],['Source and workspace',{agent_file:value.source_file,workspace:value.workspace_source},false]]){const box=el('details','',parent,'resolved-section') as HTMLDetailsElement;box.open=!!open;el('summary',String(title),box);el('pre',typeof content==='string'?content:JSON.stringify(content,null,2),box);}}
  async function editor(item:Data){
    current=item;dirty=false;renderList();const root=$('profile-editor');root.replaceChildren();$('status').textContent='';
    const heading=el('div','',root,'editor-head');el('h1',item.isNew?'New profile':item.name,heading);if(!item.isNew)button('Duplicate to local',heading,async()=>{if(dirty&&!confirm('Discard unsaved changes?'))return;try{const copy=await api('duplicate',{name:item.name});await editor({name:'',source:copy.source,revision:null,isNew:true});}catch(e){error(e);}});
    el('p',item.readOnly?'Plugin-owned profile · duplicate it to customize locally.':item.isNew?'Create a reusable launch preset. Agent definitions own the harness, instructions, and skills.':item.file,root,'subtitle');
    if(item.error)el('p',item.error,root,'error-panel');
    const tabs=el('div','',root,'tabs'),config=el('div','',root),inspect=el('div','',root);inspect.hidden=true;resolved(item.resolved,inspect);
    const configTab=button('Configuration',tabs,()=>{config.hidden=false;inspect.hidden=true;configTab.setAttribute('aria-selected','true');resolvedTab.setAttribute('aria-selected','false');},'tab');configTab.setAttribute('aria-selected','true');
    const resolvedTab=button('Resolved',tabs,()=>{config.hidden=true;inspect.hidden=false;configTab.setAttribute('aria-selected','false');resolvedTab.setAttribute('aria-selected','true');},'tab');resolvedTab.setAttribute('aria-selected','false');
    const panel=el('div','',config,'editor-panel'),name=field('Profile name',panel,item.name,item.isNew?'Lowercase letters, digits, underscores, and hyphens.':'Names are stable. Duplicate to create a differently named profile.');name.disabled=!item.isNew;
    let source=item.source as string;let sourceArea:HTMLTextAreaElement|undefined;let compose:(()=>Promise<string>)|undefined;
    if(item.isNew&&!source){
      el('h2','Launch configuration',panel);const grid=el('div','',panel,'form-grid'),label=el('label','Agent definition',grid),agent=el('select','',label) as HTMLSelectElement;for(const a of agents){const o=el('option',a,agent) as HTMLOptionElement;o.value=a;}
      const model=field('Model override',grid,'','Leave blank to inherit the agent model.');const instruction=el('p','Harness, instructions, skills, and subagents come from the selected agent. To author a new agent definition, use agent-farm init or edit your configuration files.',panel,'muted');instruction.style.fontSize='12px';
      const makeSource=()=>JSON.stringify({agent:agent.value,...(model.value.trim()?{model:{name:model.value.trim()}}:{})},null,2)+'\n';source=makeSource();agent.onchange=()=>{dirty=true;source=makeSource();};model.oninput=()=>{dirty=true;source=makeSource();};
    }else if(item.definition&&!item.error&&!item.readOnly){
      const value=item.definition;el('h2','Launch configuration',panel);const grid=el('div','',panel,'form-grid');
      const agent=field('Agent definition',grid,value.agent,'Qualified names select plugin agents, e.g. greenfield/planner.');
      const model=field('Model override',grid,value.model?.name??'','Blank inherits the agent model.');
      const reasoning=field('Reasoning override',grid,value.model?.reasoning??'','Blank inherits the agent setting.');
      const speed=field('Speed override',grid,value.model?.speed??'','Blank inherits the agent setting.');
      const argsLabel=el('label','Arguments (JSON)',panel);argsLabel.style.marginTop='18px';const args=el('textarea','',argsLabel) as HTMLTextAreaElement;args.value=JSON.stringify(value.args??{},null,2);args.oninput=()=>{dirty=true;};
      const advanced=el('details','',panel,'resolved-section');el('summary','Original YAML source · preserved on save',advanced);el('pre',source,advanced);
      compose=async()=>{const result=await api('compose',{source,agent:agent.value,model:model.value,reasoning:reasoning.value,speed:speed.value,args:args.value});return result.source;};
      el('p','Harness, instructions, and skills are inherited from the agent. Inspect them in Resolved. Changes apply to future launches only.',panel,'muted');
    }else{
      el('h2','Profile source',panel);el('p','YAML launch preset: agent, model overrides, and declared arguments. Source editing preserves comments and advanced settings.',panel,'muted');sourceArea=el('textarea','',panel,'source') as HTMLTextAreaElement;sourceArea.value=source;sourceArea.readOnly=!!item.readOnly;sourceArea.setAttribute('aria-label','Profile YAML');sourceArea.oninput=()=>{dirty=true;};
    }
    if(item.readOnly)return;
    const bar=el('div','',config,'save-bar');el('span','Changes are validated before saving.',bar,'muted');const review=el('div','',config);let pending:Data|undefined;
    const preview=button('Review changes',bar,async()=>{const version=editVersion;preview.disabled=true;review.replaceChildren();try{const input={name:name.value,source:compose?await compose():sourceArea?.value??source,revision:item.revision};const result=await api('preview',input);if(version!==editVersion){error('Changes were edited during validation. Review again.');return;}pending=input;el('h2','Review changes',review);el('p',result.file,review,'subtitle');const diff=el('div','',review,'review-grid');for(const [title,text] of [['Before',result.before??'(New profile)'],['After',result.after]]){const col=el('div','',diff);el('h3',title,col);el('pre',text,col,'raw');}resolved(result.resolved,review);button('Save profile',review,async()=>{if(!pending)return;const saving=pending;pending=undefined;try{const saved=await api('save',saving);dirty=false;await refresh();history.replaceState(null,'','#'+new URLSearchParams({view:'profiles',profile:saved.name}));await editor(saved);$('status').textContent='Profile saved. Existing sessions are unchanged.';}catch(e){error(e);}},'primary');review.scrollIntoView({behavior:'smooth',block:'start'});}catch(e){error(e);}finally{preview.disabled=false;}},'primary');
    // A reviewed snapshot is invalidated by any subsequent edit.
    config.addEventListener('input',()=>{editVersion++;pending=undefined;review.replaceChildren();});config.addEventListener('change',()=>{editVersion++;pending=undefined;review.replaceChildren();});
  }
  async function refresh(){const data=await api('list');profiles=data.profiles;agents=data.agents;$('workspace-label').textContent=data.project.split('/').filter(Boolean).pop()??data.project;$('workspace-label').title=data.project;renderList();}
  async function route(){if(dirty){if(!confirm('Discard unsaved profile changes?')){history.replaceState(null,'',lastHash);return;}dirty=false;}lastHash=location.hash;const seq=++sequence,hash=new URLSearchParams(location.hash.slice(1)),view=hash.get('view')==='profiles'?'profiles':'sessions';(document.querySelector('.shell') as HTMLElement).hidden=view!=='sessions';$('profile-manager').hidden=view!=='profiles';$('nav-sessions').setAttribute('aria-current',String(view==='sessions'));$('nav-profiles').setAttribute('aria-current',String(view==='profiles'));$('view-title').textContent=view==='sessions'?'Sessions':'Profiles';if(view!=='profiles')return;try{await refresh();if(seq!==sequence)return;const name=hash.get('profile')??profiles[0]?.name;if(name){const item=await api('get?name='+encodeURIComponent(name));if(seq===sequence)await editor(item);}else await editor({name:'',source:'',revision:null,isNew:true});}catch(e){error(e);}}
  $('new-profile').onclick=()=>{if(dirty&&!confirm('Discard unsaved profile changes?'))return;void editor({name:'',source:'',revision:null,isNew:true});};$('profile-search').oninput=renderList;
  $('nav-sessions').onclick=e=>{if(dirty&&!confirm('Discard unsaved profile changes?'))e.preventDefault();else dirty=false;};
  window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});window.addEventListener('hashchange',()=>void route());void route();
}
